# Configuração principal do FractalExplorer.
debug_global = true

[renderer]
backend = "cpu"
gpu_backend = "gl"
width = 800
height = 600
max_iterations = 256
allocation_ratio = 1
rendering_method = "direct"
precision_technique = "fixed"
precision_level = 2
perturbation_fallback = false
deallocation_ratio = 0.8
max_apparent_pixel_size_exponent = 3
min_apparent_pixel_size = 0.8
zoom_multiplier = 1.8
# Palette options: "rainbow", "inverted_rainbow" or "shade".
palette = "rainbow"
#palette = "inverted_rainbow"
#palette = "shade"
palette_period = 50.0
#starting_point = "x=-1.50, y=0.0"
#starting_point = "x: -1.484298587562009   y: 0.000113534008705   zoom: 15.787827708743960"
starting_point = "x: -1.484300952308614   y: 0.000109681311738   zoom: 37.767873168752949"
[renderer.debug]
reduced_viewport = true
reduced_viewport_allocation_ratio = 0.7
show_allocation_envelope = true
text_overlay_global = false
text_overlay_workers = false
text_overlay_layers = false
text_overlay_queue = false
middle_click_coordinate_report = false
#frame_dump_events = ["layer_created", "slow_frame"]
frame_dump_events = ["slow_frame"]
slow_frame_threshold_ms = 100

[orchestrator]
workers = 8

[orchestrator.tile]
width = 25
height = 25
